groups:
  - name: ğŸŒ ç½‘ä¸Šé‚»å±…
    desc: å¤©æ¶¯è‹¥æ¯”é‚»ã€‚
    friends:
      - name: fzf404
        desc:
        slogan: ç¤¾ä¼šä¸»ä¹‰æ¥ç­äººã€‚
        url: https://www.fzf404.art/
        avatar: https://img.fzf404.art/avatar.webp
      - name: ç”˜å°è”—
        desc:
        slogan: Ganxiaozhe's Values.
        url: https://gxzv.com/
        avatar: https://gxzv.com/lib/img/me/avatar.jpg
      - name: æå› 
        desc:
        slogan: Oh god, these stars.
        url: https://viyi.cc/
        avatar: https://viyi.cc/images/icon.png
      - name: Ayu
        desc: ç¥å¥‡çš„ç½‘ç«™ï¼Œæœ‰è¶£çš„çµé­‚ã€‚
        slogan: ä¸‰è„šçŒ«å¤šé¢æ‰‹ï¼ŒåŠªåŠ›å­¦ä¹ ä¸–ç•Œçš„ä¸€åˆ‡ã€‚
        url: https://ayu.land/
        avatar: placeholder
      - name: æ˜¼æ²³ä¸‡é‡Œ
        desc:
        slogan: ä¸€èµ·å»çœ‹æœˆäº®å§ã€‚
        url: https://tothemoonriver.icu/
        avatar: https://tothemoonriver.icu/img/avatar_hu1f7fd3bb10d1d6e480fe680f98f799d1_738451_300x0_resize_box_3.png
      - name: Nelson Boss
        desc:
        slogan: ä¸€ç›´æ¸¸åˆ°æµ·æ°´å˜è“ã€‚
        url: https://bosswnx.xyz/
        avatar: https://bosswnx.xyz/img/profile.jpg
      - name: Hzao
        desc: å¾ˆå‰å®³çš„ä½•è€å¸ˆã€‚
        slogan: ç”·å¤§å­¦ç”Ÿï¼Œç‹¬ç«‹å¼€å‘è€…ï¼ŒSSC Winnerã€‚
        url: https://blog.hzao.top/
        avatar: placeholder
      - name: æ¡‘æ¡‘
        desc: 
        slogan: Libra in your Area
        url: https://libra.wiki
        avatar: https://libra.wiki/img/avatar_hu2920716526591595834.png
      - name: å®‰æ“
        desc:
        slogan: By the power of language.
        url: https://angine.tech/
        avatar: https://avatars.githubusercontent.com/u/77579735
      - name: å±±å·è¡Œè²‰
        desc:
        slogan: å¿«è®©æˆ‘åœ¨é›ªåœ°ä¸Šæ’’ç‚¹å„¿é‡ã€‚
        url: https://www.scxho.cn/
        avatar: https://cravatar.cn/avatar/24e54d6a6ac9c59d9d5ee44c825b8c0a?&d=mm&s=200
      - name: æ˜çŸ³
        desc:
        slogan: é’æ˜¥æ— æ‚”çƒ­çˆ±ã€‚
        url: https://imakashi.eu.org/
        avatar: https://mono.imakashi.eu.org/overall/headicon2.webp
      - name: Leo's
        desc: åŒä¸º INFJã€‚
        slogan: THIS IS MY STORY.
        url: https://www.isolitude.cn/
        avatar: https://pic.isolitude.cn/2022/01/28/683727a137bb0.png
      - name: Arthals
        desc:
        slogan: æ‰€è§é«˜å±±è¿œæœ¨ï¼Œé˜”äº‘æµé£ï¼›æ‰€å¹¸å²æœˆç›ˆä½™ï¼Œäº†æ— æ‹˜æŸã€‚
        url: https://arthals.ink/
        avatar: https://arthals.ink/_next/image?url=https%3A%2F%2Fcdn.arthals.ink%2FArthals.png&w=384&q=75
      - name: Lemorica
        desc: ä¸€å¯¹å¹¸ç¦çš„ coupleã€‚
        slogan: ä¸€å®šè¦çˆ±ç€ç‚¹ä»€ä¹ˆï¼Œæ°ä¼¼è‰æœ¨å¯¹å…‰é˜´çš„é’Ÿæƒ…ã€‚
        url: https://lemorica.cn
        avatar: https://lemorica.cn/images/icon/my.png
      - name: å¼ æ´ª Heo
        desc: æå…·è®¾è®¡æ„Ÿçš„ç½‘ç«™ã€‚
        slogan: åˆ†äº«è®¾è®¡ä¸ç§‘æŠ€ç”Ÿæ´»ã€‚
        url: https://blog.zhheo.com/
        avatar: https://zhheo.com/img/icon.webp
      - name: Kai
        desc:
        slogan:
        url: https://kaiyi.cool
        avatar: https://kaiyi.cool/_astro/portrait.lBf0EGlL_1llb4H.webp
      - name: æ„§æ€
        desc:
        slogan: é“é˜»ä¸”é•¿ï¼Œè¡Œåˆ™å°†è‡³ã€‚
        url: https://kuizuo.cn
        avatar: https://kuizuo.cn/img/logo.png
      - name: æ¾èŒ¶
        desc:
        slogan: Trying to light up the dark.
        url: https://cynosura.one
        avatar: https://cynosura.one/img/profile-avatar.webp
      - name: tanscp
        desc:
        slogan: ä¸€åªæ‰“å‘¼å™œçš„çŒ«ã€‚
        url: https://tanscp.com/
        avatar: placeholder
      - name: å¤æ¢¦å–§åš£
        desc:
        slogan:
        url: https://lyuan.co
        avatar: https://purofiiru.ushiromiya.com/avatar/a16be0d8886caa88c4c6e66fd6fc48bf?s=400&r=G
      - name: Stmoonar
        slogan: A Large Language Model Developer.
        url: https://stmoonar.me
        avatar: https://os.skywt.cn/daydreamer/f1a17492-137c-45f5-af0d-7fb978407ed0
      - name: idealclover
        desc:
        slogan: Stay simple, stay naive.
        url: https://idealclover.top/
        avatar: https://cdn.idealclover.cn/Projects/homepage/icon.png
      - name: æŠ˜å½±è½»æ¢¦
        desc:
        slogan: çº¯ç²¹ã€çƒ­çˆ±ã€å‹‡æ•¢ã€‚
        url: https://nexmoe.com/
        avatar: https://nexmoe.com/
      - name: widcardw
        desc:
        slogan: ä¸æ˜¯å¤šé¢æ‰‹ã€‚
        url: https://widcard.win/
        avatar: https://avatars.githubusercontent.com/u/55699713?v=4
      - name: ä¸€è“‘çƒŸé›¨
        desc:
        slogan: ä¸€è“‘çƒŸé›¨ä»»å¹³ç”Ÿã€‚
        url: https://easyf12.top/
        avatar: https://bu.dusays.com/2023/12/24/6587c7764111a.webp
      - name: æ–¯æ–‡å­™
        desc:
        slogan:
        url: https://www.vhrise.com
        avatar: https://thirdqq.qlogo.cn/g?k=EaL0QicATH5MUdhX9NmzuVQ&b=oidb&s=0&rand=16724791560
  - name: ğŸ”¥ AdventureX
    desc: æ€»æœ‰äººå¿ƒé‡Œæœ‰ç«ç‚¬ï¼Œè€Œä¸”å½¼æ­¤èƒ½çœ‹è§ã€‚
    friends:
      - name: ç”œæª¸ Citron
        desc: 
        slogan: å‡ºç¢Ÿä½ è¨˜å¾—å¹«è¥¯ã€‚
        url: https://blog.citrons.cc/
        avatar: https://blog.citrons.cc/avatar
      - name: Steven Lynn
        desc:
        slogan: ã‚ˆã†ã“ãã€ã‚¹ãƒ‡ã‚£ãƒ–ãƒ³ã®ä¸–ç•Œ
        url: https://stv.lol
        avatar: https://cdn.statically.io/gh/stvlynn/cloudimg@master/blog/2310/00119-3903136696-glass.63hcxtyhkr00.webp
      - name: åš
        desc:
        slogan: (âœ¿â•¹â—¡â•¹) æ— å­˜åœ¨æ„Ÿå°é€æ˜ (â•¹â—¡â•¹âœ¿)
        url: https://www.huaji.store
        avatar: https://ry.huaji.store/images/logo@2x.png
      - name: äºé•¿é‡
        desc:
        slogan: åšä¸€ä¸ªè‡ªç”±è‡ªåœ¨çš„åºŸç‰©ã€‚
        url: https://rabithua.club
        avatar: https://http-1255663050.cos.ap-nanjing.myqcloud.com/blog/avatar.jpeg
      - name: é›ªèˆçµé¢œ
        desc:
        slogan: éšè‡³çˆ±è§è‡³ç¾ã€‚
        url: https://mys.forevers.love
        avatar: https://friend.s3-us-east-1.ossfiles.com/b_1f7895cd0c20cf1ea2f6903ffabafdf1.jpg
  - name: ğŸŒŸ æ—§å‹ä»¬
    desc: æˆ‘ä»¬æ›¾ç»ç»ˆæ—¥æ¸¸è¡ï¼Œåœ¨æ•…ä¹¡çš„é’å±±ä¸Šã€‚
    friends:
      - name: ZigZagK
        desc: HDU ACMer å­¦é•¿ã€‚
        slogan: Never give up fighting!
        url: https://zigzagk.top/
        avatar: https://zigzagk.top/usr/uploads/2018/07/176242131.png
      - name: Vexoben
        desc: æ¸©æŸ”å¯çˆ±çš„äºŒé©¬åŒå­¦ã€‚
        slogan: æ‚ ç„¶å¿ƒä¼šï¼Œå¦™å¤„éš¾ä¸å›è¯´ã€‚
        url: https://vexoben.lofter.com/
        avatar: https://avaimg.lf127.net/img/SUtyQ05welkyZlJXM2FmMCtZVDNTaE5LcUhvRURVSkgvVXJoMTdvd0pNYzBLVzFDWno3RkhBPT0.jpg?imageView&thumbnail=64x64&quality=90&type=jpg
      - name: SCl
        desc: æ–‡å­—è§¦åŠ¨äººå¿ƒçš„ã€ŒçŠ¶å…ƒã€åŒå­¦ã€‚
        slogan: æƒ³æŠŠæˆ‘è¯´ç»™ä½ å¬ã€‚
        url: https://aferaferafer.lofter.com/
        avatar: https://avaimg.lf127.net/img/L3hNTUkwa3F4bkNxMkhucUJYVzBtb25SVkhIcjRydU9UQm5BMzNZY2F6bEcvKzBieVdLZUhBPT0.jpg?imageView&thumbnail=128x128&quality=90&type=jpg
      - name: ymzqwq
        desc: å¾ˆå¼ºçš„ ymz åŒå­¦ã€‚
        slogan: æ˜¥å®µè‹¦çŸ­ï¼Œå°‘å¥³å‰è¿›å§ï¼
        url: https://ymzqwq.wordpress.com/
        avatar: placeholder
      - name: LLL
        desc: è‹±å§¿é£’çˆ½éœˆã€‚
        slogan: çœŸè¯šåœ°å¯¹å¾…ç”Ÿæ´»ï¼Œæˆ‘ç›¸ä¿¡ç”Ÿæ´»ä¹Ÿä¼šçœŸè¯šå¯¹æˆ‘ã€‚
        url: https://lll2560660.lofter.com/
        avatar: https://avaimg.lf127.net/img/73a4045fa68755c8/cWVMdzVOVkV6R0E0Zm5sQ1RzWkoxVXo5VTF4RDF2dUNJTzIrR3VnOFpBQT0.jpg?imageView&thumbnail=96x96&quality=90&type=jpg
      - name: CaptainSlow
        desc: ç«‹åœºåšå®šæ–—å¿—å¼ºçš„èˆ¹é•¿ã€‚
        slogan: åšæ™ºæ…§è€Œå‹¤åŠ³çš„äººã€‚
        url: https://capata.top/
        avatar: placeholder
      - name: Hangliang Ding
        url: https://foreverpiano.github.io
        avatar: placeholder
  - name: ğŸ« HNUers
    desc: We're happy, free, confused and lonely at the same time.
    friends:
      - name: B1ue1nWh1te
        desc: å¾ˆå¼ºçš„å­¦é•¿ã€‚
        slogan: çŸ¥è¡Œåˆä¸€ï¼Œå®é™è‡´è¿œã€‚
        url: https://www.seaeye.cn/
        avatar: https://img.seaeye.cn/img/seaeye/portrait.jpg
      - name: Kaisuping
        desc: å°è‹ç­é•¿ã€‚
        slogan: Hacking for fun.
        url: https://blog.kaisuping.cn/
        avatar: https://avatars.githubusercontent.com/u/93633273?v=4
      - name: Cuefe
        desc: æ¸©æŸ”å¸…æ°”çš„éƒ‘ä»£è¡¨ã€‚
        slogan: ï¼ˆâ•¯' - ')â•¯ï¸µ â”»â”â”»
        url: https://cuefe.com/
        avatar: https://f005.backblazeb2.com/file/img-buckets-oqh/2023/04/android-chrome-512x512.png
      - name: Kawasuki
        desc: æ‡‚å¾—ç”Ÿæ´»çš„å†¯ä»£è¡¨ã€‚
        slogan:
        url: https://kawatsuki.com/
        avatar: https://kawatsuki.com/MyPic/bella.png
      - name: WuJean
        desc:
        slogan: å²³éº“å±±ä¸‹ä½ å’Œæˆ‘ã€‚
        url: https://wujean.github.io/
        avatar: https://wujean.github.io/img/avatar.png
      - name: LightDust
        desc:
        slogan: This world is not perfect, but still wonderful.
        url: https://lightdust02.github.io/
        avatar: https://lightdust02.github.io/images/doge.png
      - name: è´°çŒ¹çš„å°çª
        desc:
        slogan: ç”¨è¿™ç”Ÿå‘½ä¸­çš„æ¯ä¸€ç§’ï¼Œç»™è‡ªå·±ä¸€ä¸ªä¸åæ‚”çš„æœªæ¥ã€‚
        url: https://noionion.top/
        avatar: placeholder
      - name: Mufanc
        desc:
        slogan: æ˜Ÿæ²³ç’€ç’¨ï¼Œå‡¡å°˜ç‚¹ç‚¹ã€‚
        url: https://blog.mufanc.xyz/
        avatar: https://blog.mufanc.xyz/assets/images/avatar.jpeg
      - name: Ripple
        desc:
        slogan: è¶…é«˜æ ¡çº§çš„æ¸¸æˆç©å®¶ï¼
        url: https://hiripple.com/
        avatar: https://ripple.eu.org/Ripplelog-icon.png
      - name: CYP0633
        desc:
        slogan: æˆ‘ä»¬éƒ½æ›¾æ˜¯æµ·æ»©ä¸Šç©æ²™å ¡çš„å­©å­ã€‚ç°åœ¨ä»æ˜¯ï¼Œåªä¸è¿‡ä¸åœ¨æµ·æ»©ä¸Šç½¢äº†ã€‚
        url: https://cyp0633.icu/
        avatar: https://cyp0633-public-resource.oss-cn-qingdao.aliyuncs.com/blog/cyp0633-icon.jpg
      - name: Ekennis
        desc:
        slogan: Ekke ã® Space.
        url: https://noobzyk.top/
        avatar: https://ekkepic.oss-cn-beijing.aliyuncs.com/img/20210701163204.png
