groups:
  - name: ğŸŒŸ å…¬å…±æœåŠ¡
    services:
      - name: Blog
        app: Typecho æ—§åšå®¢
        url: https://blog.skywt.cn
        method: Docker, Upyun
      # - name: Whisper
      #   app: WordPress å­åšå®¢
      #   url: https://whisper.skywt.cn
      #   method: Docker ğŸš§
      - name: Write
        app: Typecho æ‰‹å†™åšå®¢
        url: https://write.skywt.cn
        method: Docker, Upyun
      - name: Books
        app: Calibre-web ç”µå­ä¹¦ç®¡ç†
        url: https://books.skywt.cn
        method: Docker
      - name: Drop
        app: Snapdrop æ–‡ä»¶ä¼ è¾“
        url: https://drop.skywt.cn
        method: Docker
      - name: CV
        app: WebCV åœ¨çº¿ç®€å†
        url: https://cv.skywt.cn
        method: Vercel, DogeCloud
  - name: ğŸ‘¨â€ğŸ’» æ•ˆç‡å·¥å…·
    services:
      - name: Memos
        app: memos å¡ç‰‡ç¬”è®°
        url: https://memos.skywt.cn
        method: Docker
      - name: Password
        app: VaultWarden å¯†ç ç®¡ç†
        url: https://pass.skywt.cn
        method: Docker
      - name: Chat
        app: NextChat GPT å®¢æˆ·ç«¯
        url: https://chat.skywt.cn
        method: Vercel
      - name: ChatGPT
        app: Better ChatGPT å®¢æˆ·ç«¯
        url: https://chatgpt.skywt.cn
        method: Vercel
      - name: RSS
        app: FreshRSS åœ¨çº¿é˜…è¯»å™¨
        url: https://rss.skywt.cn
        method: Docker
      - name: RSSHub
        app: RSSHub
        url: https://rsshub.skywt.cn
        method: Docker
      - name: WeRSS
        app: å¾®ä¿¡å…¬ä¼—å· RSS
        url: https://werss.skywt.cn
        method: Docker
      - name: Archive
        app: ArchiveBox ç½‘é¡µå­˜æ¡£
        url: https://archive.skywt.cn
        method: Docker
  - name: ğŸ› ï¸ å¼€å‘ä¸è¿ç»´
    services:
      - name: Git
        app: Gitea ä»£ç ä»“åº“
        url: https://git.skywt.cn
        method: Docker
      - name: Code
        app: Code-server ç¼–è¾‘å™¨
        url: https://code.skywt.cn
        method: Docker
      - name: Frp
        app: Frp å†…ç½‘ç©¿é€
        url: https://frp.skywt.cn
        method: Docker
      - name: VPN
        app: Headscale è™šæ‹Ÿä¸“ç”¨ç½‘ç»œ
        url: https://vpn.skywt.cn
        method: Docker
      - name: Push
        app: Bark iOS æ¨é€æœåŠ¡
        url: https://push.skywt.cn
        method: Docker
      - name: Minecraft
        app: Minecraft æœåŠ¡å™¨
        url:
        method: Docker ğŸ’¤
        status: stopped
  - name: ğŸ—ƒï¸ æ–‡ä»¶å­˜å‚¨
    services:
      - name: Cloud
        app: Nextcloud äº‘å¥—ä»¶
        url: https://cloud.skywt.cn
        method: Docker
      - name: Drive
        app: Cloudreve äº‘ç›˜
        url: https://drive.skywt.cn
        method: Docker
      - name: WebDAV
        app: WebDAV
        url: https://webdav.skywt.cn
        method: Docker
      # - name: Object Storage
      #   app: MinIO å¯¹è±¡å­˜å‚¨
      #   url: https://os.skywt.cn
      #   method: Docker
  - name: âš™ï¸ ç®¡ç†å·¥å…·
    services:
      - name: Auth
        app: Keycloak å•ç‚¹ç™»å½•
        url: https://auth.skywt.cn
        method: Docker
      - name: Analytics
        app: Matomo è®¿å®¢ç»Ÿè®¡
        url: https://analytics.skywt.cn
        method: Docker
      - name: Console
        app: Cockpit æ§åˆ¶é¢æ¿
        url: https://console.skywt.cn
        method: Systemd
      # - name: pgAdmin
      #   app: pgAdmin
      #   url: https://pgadmin.skywt.cn
      #   method: Docker ğŸ’¤
      #   status: stopped
      - name: phpMyAdmin
        app: phpMyAdmin
        url: https://phpmyadmin.skywt.cn
        method: Docker
      - name: Uptime
        app: Upptime æœåŠ¡å™¨ç›‘æ§
        url: https://uptime.skywt.cn
        method: GitHub Actions
      - name: Status
        app: Netdata æœåŠ¡å™¨ç›‘æ§
        url: https://status.skywt.cn
        method: Systemd
      # - name: Dashboard
      #   app: Grafana æ•°æ®é¢æ¿
      #   url: https://dash.skywt.cn
      #   method: Docker
