friends:
  - name: fzf404
    desc: å·¦æ´¾ç¤¾ä¼šä¸»ä¹‰æ¥ç­äºº
    url: https://www.fzf404.art/
    avatar: https://img.fzf404.art/avatar.webp
  - name: ç”˜å°è”—
    desc: Ganxiaozhe's Values
    url: https://gxzv.com/
    avatar: https://gxzv.com/lib/img/me/avatar.jpg
  - name: æå› 
    desc: ã€ŒOh god, these stars. ã€
    url: https://viyi.cc/
    avatar: https://viyi.cc/images/icon.png
  - name: Ayu
    desc: ã€Œä¸‰è„šçŒ«å¤šé¢æ‰‹ï¼ŒåŠªåŠ›å­¦ä¹ ä¸–ç•Œçš„ä¸€åˆ‡ã€‚ã€
    url: https://ayu.land/
    avatar: ./visitor.png
  - name: æ˜¼æ²³ä¸‡é‡Œ
    desc: ã€Œä¸€èµ·å»çœ‹æœˆäº®å§ã€‚ã€
    url: https://tothemoonriver.icu/
    avatar: https://tothemoonriver.icu/img/avatar_hu1f7fd3bb10d1d6e480fe680f98f799d1_738451_300x0_resize_box_3.png
  - name: Hzao
    desc: ã€Œã€
    url: https://blog.hzao.top/
    avatar: ./visitor.png
  - name: å®‰æ“
    desc: ã€ŒBy the power of language. ã€
    url: https://angine.tech/
    avatar: ./visitor.png
  - name: widcardw
    desc: ã€Œä¸æ˜¯å¤šé¢æ‰‹ã€‚ã€
    url: https://widcard.win/
    avatar: https://avatars.githubusercontent.com/u/55699713?v=4
  - name: å±±å·è¡Œè²‰
    desc: ã€Œå¿«è®©æˆ‘åœ¨é›ªåœ°ä¸Šæ’’ç‚¹å„¿é‡ã€‚ã€
    url: https://www.scxho.cn/
    avatar: https://cravatar.cn/avatar/24e54d6a6ac9c59d9d5ee44c825b8c0a?&d=mm&s=200
  - name: æ˜çŸ³
    desc: ã€Œé’æ˜¥æ— æ‚”çƒ­çˆ±ã€‚ã€
    url: https://imakashi.eu.org/
    avatar: https://imakashi.eu.org/asset/overall/img/headicon.webp
  - name: Leo's
    desc: ã€ŒTHIS IS MY STORY. ã€
    url: https://www.isolitude.cn/
    avatar: https://pic.isolitude.cn/2022/01/28/683727a137bb0.png
  - name: idealclover
    desc: ã€ŒStay simple, stay naive. ã€
    url: https://idealclover.top/
    avatar: https://cdn.idealclover.cn/Projects/homepage/icon.png
  - name: å¼ å“„ Heo
    desc: ã€Œåˆ†äº«è®¾è®¡ä¸ç§‘æŠ€ç”Ÿæ´»ã€‚ã€
    url: https://blog.zhheo.com/
    avatar: https://zhheo.com/img/icon.webp
  - name: ä¸€è“‘çƒŸé›¨
    desc: ã€Œä¸€è“‘çƒŸé›¨ä»»å¹³ç”Ÿã€‚ã€
    url: https://easyf12.top/
    avatar: https://bu.dusays.com/2023/12/24/6587c7764111a.webp
  - name: æŠ˜å½±è½»æ¢¦
    desc: ã€Œçº¯ç²¹ã€çƒ­çˆ±ã€å‹‡æ•¢ã€‚ã€
    url: https://nexmoe.com/
    avatar: https://nexmoe.com/
  # - name: Sun
  #   desc: ã€Œè‡ªå¼ºä¸æ¯ï¼Œåšå¾·è½½ç‰©ã€‚ã€
  #   url: https://www.iaesun.com/

  - name: ZigZagK
    desc: HDU ACMer å­¦é•¿
    url: https://zigzagk.top/
    avatar: https://zigzagk.top/usr/uploads/2018/07/176242131.png
  - name: Vexoben
    desc: æ¸©æŸ”å¯çˆ±çš„äºŒé©¬åŒå­¦
    url: https://vexoben.lofter.com/
    avatar: https://avaimg.lf127.net/img/SUtyQ05welkyZlJXM2FmMCtZVDNTaE5LcUhvRURVSkgvVXJoMTdvd0pNYzBLVzFDWno3RkhBPT0.jpg?imageView&thumbnail=64x64&quality=90&type=jpg
  - name: SCl
    desc: æ–‡å­—è§¦åŠ¨äººå¿ƒçš„ã€ŒçŠ¶å…ƒã€åŒå­¦
    url: https://aferaferafer.lofter.com/
    avatar: https://avaimg.lf127.net/img/L3hNTUkwa3F4bkNxMkhucUJYVzBtb25SVkhIcjRydU9UQm5BMzNZY2F6bEcvKzBieVdLZUhBPT0.jpg?imageView&thumbnail=128x128&quality=90&type=jpg
  # - name: StarlightXXY
  #   desc: å¾ˆä¼˜ç§€çš„å°èƒ¡åŒå­¦
  #   url: https://starlightxyy.cn
  - name: ymzqwq
    desc: å¾ˆå¼ºçš„ ymz åŒå­¦
    url: https://ymzqwq.wordpress.com/
    avatar: ./visitor.png
  - name: LLL
    desc: è‹±å§¿é£’çˆ½éœˆ
    url: https://lll2560660.lofter.com/
    avatar: https://lll2560660.lofter.com/
  - name: æ¨å°èŠ±
    desc: æ¨å°èŠ± ğŸŒ¸ï½
    url: https://acheing.com/
    avatar: ./visitor.png
  - name: CaptainSlow
    desc: ç«‹åœºåšå®šæ–—å¿—å¼ºçš„èˆ¹é•¿
    url: https://capata.top/
    avatar: ./visitor.png

  - name: B1ue1nWh1te
    desc: å¾ˆå¼ºçš„å­¦é•¿ã€‚ã€Œäº‘å·äº‘èˆ’ï¼Œå¤„ä¹‹æ³°ç„¶ã€‚ã€
    url: https://www.seaeye.cn/
    avatar: https://img.seaeye.cn/img/seaeye/portrait.jpg
  # - name: BKCat
  #   desc: å°è‹ç­é•¿ã€‚ã€Œæˆå¹´äººè¦å­¦ä¼šåšè‡ªå·±çš„äº‹æƒ…ã€‚ã€
  #   url: https://bkcat.cn/
  #   avatar: ./visitor.png
  - name: WuJean
    desc: ã€Œå²³éº“å±±ä¸‹ä½ å’Œæˆ‘ã€‚ã€
    url: https://wujean.github.io/
    avatar: https://wujean.github.io/img/avatar.png
  - name: è´°çŒ¹çš„å°çª
    desc: ã€Œç”¨è¿™ç”Ÿå‘½ä¸­çš„æ¯ä¸€ç§’ï¼Œç»™è‡ªå·±ä¸€ä¸ªä¸åæ‚”çš„æœªæ¥ã€‚ã€
    url: https://noionion.top/
    avatar: ./visitor.png
  - name: Ripple
    desc: ã€Œè¶…é«˜æ ¡çº§çš„æ¸¸æˆç©å®¶ï¼ã€
    url: https://hiripple.com/
    avatar: https://ripple.eu.org/Ripplelog-icon.png
  - name: CYP0633
    desc: ã€Œæˆ‘ä»¬éƒ½æ›¾æ˜¯æµ·æ»©ä¸Šç©æ²™å ¡çš„å­©å­ã€‚ç°åœ¨ä»æ˜¯ï¼Œåªä¸è¿‡ä¸åœ¨æµ·æ»©ä¸Šç½¢äº†ã€‚ã€
    url: https://cyp0633.icu/
    avatar: https://cyp0633-public-resource.oss-cn-qingdao.aliyuncs.com/blog/cyp0633-icon.jpg
  - name: Mufanc
    desc: ã€Œæ˜Ÿæ²³ç’€ç’¨ä¸¶å‡¡å°˜é»é»ã€‚ã€
    url: https://blog.mufanc.xyz/
    avatar: https://blog.mufanc.xyz/assets/images/avatar.jpeg
  - name: Ekennis
    desc: ã€ŒEkke ã® Spaceã€
    url: https://noobzyk.top/
    avatar: https://ekkepic.oss-cn-beijing.aliyuncs.com/img/20210701163204.png
